### ISSUE TITLE
A few test failures on OpenJDK 8

### ISSUE THREAD

**Issue by pangloss** [pangloss/pacer#28]
I used this version: http://code.google.com/p/openjdk-osx-build/downloads/detail?name=OpenJDK-OSX-8-x64-jdk-b53-20120824.dmg&can=2&q=

**Comment by pangloss** [comment]
Closing. Appears to work on Java 8 now.

**Comment by dcolebatch** [comment]
Which branch of pacer are you testing, master still has 10 failed tests on Java 8 for me...

**Comment by dcolebatch** [comment]
FYI - I'm using Oracle's JDK[1] as it is officially supported by Neo4j

1: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by dcolebatch** [comment]
Good call :)
