### ISSUE TITLE
NameError: undefined field 'pathEnabled' for class 'Pacer::Pipes::RubyPipe'

### ISSUE THREAD

**Issue by jayniz** [pangloss/pacer#37]
Just upgraded jruby (to 1.7.2) and pacer (to 1.1.1, with pacer-neo4j-2.1.0) and now get this error when trying to start my app:

    NameError: undefined field 'pathEnabled' for class 'Pacer::Pipes::RubyPipe'
                field_reader at org/jruby/java/proxies/JavaProxy.java:287
                    RubyPipe at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer/pipe/ruby_pipe.rb:3
                       Pipes at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer/pipe/ruby_pipe.rb:2
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer/pipe/ruby_pipe.rb:1
                     require at org/jruby/RubyKernel.java:1027
      require_with_backports at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/backports-2.6.4/lib/backports/tools.rb:314
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer/pipes.rb:1
                     require at org/jruby/RubyKernel.java:1027
      require_with_backports at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/backports-2.6.4/lib/backports/tools.rb:314
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer/pipes.rb:33
                     require at org/jruby/RubyKernel.java:1027
      require_with_backports at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/backports-2.6.4/lib/backports/tools.rb:314
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer/loader.rb:1
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer/loader.rb:19
                     require at org/jruby/RubyKernel.java:1027
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer.rb:1
                        each at org/jruby/RubyArray.java:1613
                       Pacer at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer.rb:42
                        each at org/jruby/RubyArray.java:1613
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@sheldon/gems/pacer-1.1.1-java/lib/pacer.rb:25
                      (root) at /Users/jannis/.rvm/gems/jruby-1.7.2@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:1
                      (root) at ./console:10

This is with an embedded neo4j version 1.8.1 and the ruby gem neo4j.rb version 2.2.0

**Comment by pangloss** [comment]
I think this issue is obsolete. Ruby pipes are being rewritten in pure Java.
