### ISSUE TITLE
Component 'org.neo4j.kernel.extension.KernelExtensions@1eb458fd' failed to initialize. 

### ISSUE THREAD

**Issue by ettomatic** [pangloss/pacer#38]
I'm unable to follow your readme example on Interoperation with the neo4j gem:

    >> require 'neo4j'
    => true
    >> require 'pacer-neo4j'
    => true
    >> Neo4j.db.start
    I, [2013-01-29T16:51:19.924000 #12485]  INFO -- : Starting local Neo4j using db    /home/ettober/code/neo4j/serv1/db using Java::OrgNeo4jKernel::EmbeddedGraphDatabase
    Java::JavaLang::RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@1eb458fd' failed to initialize. Please see attached cause exception.
        from org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:258)
        from org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:88)
        from org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:75)

Issue do not appear if I only require the Neo4j gem and start the db.

Context:
jruby 1.7.2
neo4j 2.2.3
pacer 1.1.1
pacer-neo4j 2.1.0

**Comment by pangloss** [comment]
Pacer's new better Jar dependency management should prevent this problem in the future.
