### ISSUE TITLE
Tinkerpop and Pacer Versioning

### ISSUE THREAD

**Issue by tobowers** [pangloss/pacer#44]
Hi,

I commented on a pull request about upgrading to tinkerpop 2.3.0 (and my trouble upgrading to 2.4.0-SNAPSHOT).  I've also previously had a pull requested rejected (for GOOD cause!) separating jars from the Pacer repo.

I've been thinking a lot about how pacer could make this easier on those of us trying (or having-to-for-bugs) remain on the bleeding edge.  

I have three ideas:

1. Keep the JARS in Pacer, but add a unless defined?() before the require, that way in development, or even in production, I could include my own jars before Pacer and have Pacer use those.
2. Version Pacer in line with tinkerpop... so the version number at release of pacer would match tinkerpop - then you know what your'e getting. If there's a pacer-specific update - tack it on at the end.  And... use .pre for the snapshot releases... so right now there would probably be a pacer 2.2.0, a pacer 2.3.0 and a pacer 2.4.0.pre  And if pacer needed a bug fix, it'd get 2.2.0.1, 2.3.0.1 and 2.4.0.pre2
3.  This one you have already rejected, but putting the jars into a different gem and having pacer have only a loose dependency on them... like the zk gem does: https://github.com/slyphon/zookeeper_jar  That way, I would only fork the jars repo and update there.

I, personally, lean towards doing 1 *and* 2. What are your thoughts?  I'm happy to submit a pull request with any/all of this or any better ideas.  Right now, we have had to fork pacer to use updated tinkerpop and that poses serious challenges because pacer has a build step... so I can't just add a git: git@mypacerepo to my Gemfile... In fact, I'm at a little bit of a loss as to how to use my forked gem easily in prod without publishing it to rubygems.

So that's a few ideas and the *why* of allowing easier swapping of tinkerpop. I'm open to any and all suggestions.

**Comment by pangloss** [comment]
This has finally been resolved using lock_jar!
