### ISSUE TITLE
JRuby warning about ambiguous Java method

### ISSUE THREAD

**Issue by joeyfreund** [pangloss/pacer#70]
Here is the message I am seeing:

```
/home/vagrant/.rvm/gems/jruby-1.7.18/gems/pacer-2.0.12-java/lib/pacer/core/route.rb:519 warning: ambiguous Java methods found, using setStarts(java.util.Iterator)
```

Here is a [description of a possible solution](https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby#calling-masked-or-unreachable-java-methods-with-java_send).

Line 519 should probably change from 

```
start.setStarts src
```

to

```
start.java_send :setStarts, [java.util.Iterator], src
```

**Comment by pangloss** [comment]
Yeah, that's probably the correct fix. Do you want to throw that into a pull request?

**Comment by joeyfreund** [comment]
Unfortunately, it wasn't so simple.

The change I proposed resulted in the following error:
```
cannot convert instance of class org.jruby.RubyModule to class java.lang.Class
```
This is related to the fact that `java.util.Iterator` is an interface, and not a concrete class.

There is a "fix" in [this stackOverflow thread](http://stackoverflow.com/questions/6238734/jruby-calls-the-wrong-method). I have verified that the fix works, but I feel that it's better to avoid it, live with the warning message, and not make unnecessary `Class.forName` method calls.

Your thoughts?

**Comment by pangloss** [comment]
I haven't tried this yet, but would the following work? If not I can try it out tomorrow...

```
start.java_send :setStarts, [java.util.Iterator.java_class], src
```

**Comment by joeyfreund** [comment]
Here is the result of `bundle exec autotest`, when using `start.java_send :setStarts, [java.util.Iterator.java_class], src`:

```
Finished in 9.08 seconds
1192 examples, 6 failures, 4 pending

Failed examples:

rspec ./spec/pacer/filter/loop_filter_spec.rb:91 # tg Pacer::Filter::LoopFilter#loop control block should have correct paths with control block paths
rspec ./spec/pacer/filter/loop_filter_spec.rb:99 # tg Pacer::Filter::LoopFilter#loop control block should have correct paths without control block paths
rspec ./spec/pacer/filter/loop_filter_spec.rb:107 # tg Pacer::Filter::LoopFilter#loop control block should loop or emit or loop_and_emit as needed
rspec ./spec/pacer/filter/loop_filter_spec.rb:63 # tg Pacer::Filter::LoopFilter#loop control block project tree should exhaust the depths list
rspec ./spec/pacer/filter/loop_filter_spec.rb:68 # tg Pacer::Filter::LoopFilter#loop control block project tree should have the right results
rspec ./spec/pacer/filter/loop_filter_spec.rb:137 # tg Pacer::Filter::LoopFilter#repeat with a range should be equivalent to executing each path separately
```

I also verified that these 6 failures are related to this change. I changed that line back to `start.setStarts src` and got:

```
Finished in 10.19 seconds
1192 examples, 0 failures, 4 pending
```

**Comment by pangloss** [comment]
I wouldn't be surprised if "source_iterator" was actually incorrectly returning an Iterable rather than an actual Iterator somewhere in the loop logic.
