### ISSUE TITLE
Loop step

### ISSUE THREAD

**Issue by rrphotosoft** [pangloss/pacer#72]
HI, 
I just discovered your library! Great work.
I just thought I'd ask how to implement the Loop step,?
Can't seem to find it/
Furthermore is it possible, to employ a simple flowrank pattern caclulation like so:

      g.v(12).as('x').out.groupCount(m){it.name}.loop('x'){c++ < 1000}.iterate()

This is on the gremlin page:
https://github.com/tinkerpop/gremlin/wiki/Flow-Rank-Pattern

Thanks again,
BHargav.

**Comment by pangloss** [comment]
Yes, Pacer can express a traversal like that. The direct translation would be something like this:

```ruby
g.vertex(12).all { |v| v.out }.limit(1000).group_count(:name)
```

We've got a bit of documentation on the `all` step along with some alternatives [here](https://github.com/pangloss/pacer/wiki/Graph%20Traversals%20with%20Pacer%20Routes#looping-through-repeating-graph-structures).

Enjoy!

Darrick

**Comment by rrphotosoft** [comment]
Thank you so much for your help , and I applaud your efforts in combining a gremlin with Ruby. It is quite literally the Brangelina of graph databasing, although I don't know which is which :)

**Comment by pangloss** [comment]
I'll take that as a complement even though Pacer predates the Groovy implementation of Gremlin ;)
